University/Models/Course.cs
using System.Collections.Generic;

namespace University.Models
{
  public class Course
  {
    public Course()
    {
      this.JoinEntities = new HashSet<CourseDepartmentStudent>();
    }
    public int CourseId { get; set; }
    public string Name { get; set; }
    public int Number { get; set; }

    public int MyInt { get; set; }
    public virtual ICollection<CourseDepartmentStudent> JoinEntities { get; set; }

    public string NameNumber
    {
      get
      {
        return Name + Number;
      }
    }
  }
}

University/Models/CourseDepartmentStudent.cs
namespace University.Models
{
  public class CourseDepartmentStudent
  {
    public int CourseDepartmentStudentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public int DepartmentId { get; set; }
    public virtual Student Student { get; set; }
    public virtual Course Course { get; set; }
    public virtual Department Department { get; set; }
  }
}

University/Models/Department.cs
using System.Collections.Generic;

namespace University.Models
{
  public class Department
  {
    public Department()
    {
      this.JoinEntities = new HashSet<CourseDepartmentStudent>();
    }
    public int DepartmentId { get; set; }
    public string Name { get; set; }
    // public int Number { get; set; }

    // public int MyInt { get; set; }
    public virtual ICollection<CourseDepartmentStudent> JoinEntities { get; set; }

    // public string NameNumber
    // {
    //   get
    //   {
    //     return Name + Number;
    //   }
    // }
  }
}

University/Models/DesignTimeDBContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace University.Models
{
  public class UniversityContextFactory : IDesignTimeDbContextFactory<UniversityContext>
  {

    UniversityContext IDesignTimeDbContextFactory<UniversityContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new UniversityContext(builder.Options);
    }
  }
}

University/Models/Student.cs
using System.Collections.Generic;
using System;

namespace University.Models
{
  public class Student
  {
    public Student()
    {
      this.JoinEntities = new HashSet<CourseDepartmentStudent>();

    }

    public int StudentId { get; set; }
    public string Name { get; set; }
    public DateTime Enrollment { get; set; }
    public virtual ICollection<CourseDepartmentStudent> JoinEntities { get; }
  }
}

University/Models/UniversityContext.cs
using Microsoft.EntityFrameworkCore;
namespace University.Models
{
  public class UniversityContext : DbContext
  {
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseDepartmentStudent> CourseDepartmentStudent { get; set; }
    public UniversityContext(DbContextOptions options) : base(options) { }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

University/Controllers/CoursesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using University.Models;
using System.Collections.Generic;
using System.Linq;


namespace University.Controllers
{
  public class CoursesController : Controller
  {
    private readonly UniversityContext _db;

    public CoursesController(UniversityContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
          .Include(course => course.JoinEntities)
          .ThenInclude(join => join.Student)
          .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

University/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace University.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

University/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using University.Models;
using System.Linq;

namespace University.Controllers
{
  public class StudentsController : Controller
  {
    private readonly UniversityContext _db;
    public StudentsController(UniversityContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }

    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
      .Include(student => student.JoinEntities)
      .ThenInclude(join => join.Course)
      .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "NameNumber");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      _db.SaveChanges();
      if (CourseId != 0)
      {
        _db.CourseDepartmentStudent.Add(new CourseDepartmentStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View(thisStudent);
    }
    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseDepartmentStudent.Add(new CourseDepartmentStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View(thisStudent);
    }
    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseDepartmentStudent.Add(new CourseDepartmentStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseDepartmentStudent.FirstOrDefault(entry => entry.CourseDepartmentStudentId == joinId);
      _db.CourseDepartmentStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

University/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h4>Add a new course</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Number)
  @Html.TextBoxFor(model => model.Number)
  <input type="submit" value="Add new course" />
}
<p>@Html.ActionLink("Show all courses", "Index")</p>

University/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

University/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course;

<h2>Course Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This course does not contain any students</p>
}
else
{
  <h4>Students the course contains:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Student.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Back to courses", "Index")</p>
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>

University/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

University/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using University.Models;

<h1>Courses</h1>

@if (@Model.Count == 0)
{
  <h3>No courses have been added yet!</h3>
}

<ul>
  @foreach (Course course in Model)
  {
    <li>@Html.ActionLink($"{course.Name}", "Details", new { id = course.CourseId }) | @course.Number</li>
  }
</ul>

<p>@Html.ActionLink("Add new course", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

University/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Marney's Log planting School!</h1>
<p>@Html.ActionLink("See all students", "Index", "Students")</p>
<p>@Html.ActionLink("See all courses", "Index", "Courses")</p>

University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Marney's Log Hugging and planting school!</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  @RenderBody()
</body>

</html>

University/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student
<h2>Add a course</h2>
<h4>Add a course for this student: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)
  @Html.Label("Select course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

University/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h4>Add a new Student</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Enrollment)
  @Html.EditorFor(model => model.Enrollment)

  @Html.Label("Select Course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Add new student" class="btn btn-outline-success">
}
<p>@Html.ActionLink("Show all students", "Index")</p>

University/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />

}
@Html.ActionLink("Back to List", "Index")

University/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h2>Student Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This student is not enrolled in any courses</p>
}
else
{
  <h4>Courses that the student is enrolled in:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Course.Name</li>
    }
  </ul>
}
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Student", "Edit", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>

University/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Enrollment)
  @Html.EditorFor(model => model.Enrollment)

  @Html.Label("Select Course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("View all students", "Index")</p>

University/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using University.Models;
@model List<University.Models.Student>;

<h1>Students</h1>

@if (@Model.Count == 0)
{
  <h3>No students have been added!</h3>
}

@foreach (Student student in Model)
{
  <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId })</li>
}

<p>@Html.ActionLink("Add new student", "Create", "Students")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>